# NumPy Array

In [3]:
import numpy as np

In [2]:
mylist = [1,2,3,4,5,6,7,8]
np.array(mylist)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
#Create matrix

mymatlist = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mymatlist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Built in Methods

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,10,3)

array([0, 3, 6, 9])

#### Zero's and one's

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

### line spacing !

In [13]:
np.linspace(0,11,3)

array([ 0. ,  5.5, 11. ])

In [19]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## eye !

Creats Identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

To create random number arrays, there are many ways to create the array

In [21]:
np.random.rand(2)

array([0.95894493, 0.75685939])

In [26]:
np.random.randint(2,100)

52

In [28]:
np.random.rand(3,2)

array([[0.37256179, 0.42836616],
       [0.88485561, 0.63600578],
       [0.06173614, 0.3007241 ]])

In [30]:
np.random.randn(3)

array([-1.07845375,  1.88029752,  0.33057623])

In [31]:
np.random.randn(2,3)

array([[-0.47952676,  0.03044047, -1.66655794],
       [-1.10182437,  0.30526714, -1.23072102]])

random.rand -> Gives uniform distribution numbers
where as
random.randn - > Gives standard distribution numbers

In [32]:
np.random.randint(1,100)

52

In [33]:
np.random.randint(1,100,10)

array([51, 76,  4, 32, 82, 19, 14,  2, 94, 45])

random.randint -> gives random integer from low to high range

In [34]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [44]:
myarr = np.arange(25)

In [45]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [50]:
myarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
myarr.max()

24

In [52]:
myarr.min()

0

In [53]:
myarr.argmax()

24

In [54]:
myarr.argmin()

0

In [55]:
myarr.shape

(25,)

In [58]:
myarr.shape

(25,)

In [59]:
myarr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [60]:
myarr.reshape(1,25).shape

(1, 25)

In [61]:
myarr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [62]:
myarr.reshape(25,1).shape

(25, 1)

In [63]:
myarr.dtype

dtype('int32')

In [66]:
myarr.ndim

1

In [67]:
myarr.ndim

1

In [72]:
arry = np.arange(0,20)

In [73]:
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [90]:
lisarray = arry.reshape(4,5)

In [91]:
lisarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
lisarray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [99]:
lisarray[1:2,1:]

array([[6, 7, 8, 9]])

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[0:12]= 100

In [8]:
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])